export type LpLocale = 'en' | 'ja' | 'zh';

export function getLpLocale(locale: string): LpLocale {
  return locale === 'ja' || locale === 'zh' ? locale : 'en';
}

export const lpCopy = {
  ja: {
    metaTitle: 'Mother Vegetable FMCG | ストーリーのあるプロダクト×地球最初の植物の力',
    metaDescription: 'ストーリーのあるプロダクトと地球最初の植物の力から生まれるMother Vegetable FMCG。',
    heroTitle: 'Mother Vegetable FMCG',
    heroSubbrand: 'ALL MADE IN JAPAN',
    heroTagline: 'ストーリーのあるプロダクト×地球最初の植物の力',
    heroCta: 'MV Productをチェックする',
    aboutTitle: ['開発者ストーリーと', '地球最初の植物との融合'],
    aboutLead: ['日本各地で育まれてきた食文化や技術。', '未来を想像する子どもたちのアイデア。', 'アスリートや生産者たちの挑戦。'],
    aboutBody: ['Mother Vegetable FMCGは、', '「大切な人たちのストーリー」と', '地球最初の生命を融合しながら、', '地路・健康・未来をつなぐ', '新しいプロダクトへ進化していきます。'],
    productsTitle: ['Mother Vegetableから生まれた', '2つの「地球最古の生命の力」が', '全てのアイテムに'],
    achieveLead: '高たんぱく質＋全48種類の天然栄養',
    achieveBody: ['Mother Vegetableから生まれた高栄養食品「Achieve」。', 'たんぱく質、ミネラル、ビタミン、フィコシアニンなどを含み、', '食事、調味料、飲料、ペット、スポーツ栄養まで幅広く活用できます。', '現代の食に、地球最古の生命力を加える素材です。'],
    achieveCta: 'Achieveとのコラボ商品はこちら',
    confidenceLead: '純度97%の天然シリカで、やさしく整える。',
    confidenceBody: ['Mother Vegetableから生まれた白いパウダー「Confidence」。', '育つ過程で、純度97%の非晶質シリカを生み出します。', '医薬部外品原料規格もクリアしたシリカは', '肌や髪、愛するペットにも使用可能で、', '化粧水やシャンプーに混ぜて1ランク上のアイテムに。'],
    confidenceCta: 'Confidenceとのコラボ商品はこちら',
    storySubtitle: ['人の想い。日本の魅力。地球の力。', 'そのすべてを取り込んだプロダクト。'],
    storyDiagramTitle: 'MV Productをつくる3つの力',
    force1Title: '生産者の想い',
    force1Description: '誰のために、どんな未来を想い作られたのか。',
    force2Title: ['日本の素材', '地域の魅力'],
    force2Description: '土地に根づいた素材、文化、技術、物語。',
    force3Title: 'Mother Vegetableの力',
    force3Description: '地球最古の生命が持つ、栄養・浄化・再生の力。',
    searchTitle: ['物語・人・国から', 'いますぐ検索してみよう'],
    searchSubtitle: '探すこと自体が、楽しくなるECへ',
    searchOptions: ['物語で探す', '発案者で探す', '国で探す'],
    searchNote: '探すこと自体が楽しくなる、Mother Vegetableの検索体験です。',
    searchCta: '商品一覧で検索体験を試す →',
  },
  en: {
    metaTitle: 'Mother Vegetable FMCG | Story-led products powered by Earth’s first plant life',
    metaDescription: 'Mother Vegetable FMCG creates story-led products powered by the life force of Earth’s first plant life.',
    heroTitle: 'Mother Vegetable FMCG',
    heroSubbrand: 'ALL MADE IN JAPAN',
    heroTagline: 'Story-led products × the power of Earth’s first plant life',
    heroCta: 'Explore MV Product',
    aboutTitle: ['Developer stories', 'meet Earth’s first plant'],
    aboutLead: ['Food cultures and craft nurtured across Japan.', 'Ideas from children imagining the future.', 'The challenges of athletes and producers.'],
    aboutBody: ['Mother Vegetable FMCG evolves', 'by merging the stories of people we care about', 'with Earth’s first life,', 'connecting the Earth, health, and the future', 'into a new generation of products.'],
    productsTitle: ['Born from Mother Vegetable', 'Two powers of Earth’s oldest life', 'in every item'],
    achieveLead: 'High protein + 48 natural nutrients',
    achieveBody: ['Achieve is a high-nutrition food born from Mother Vegetable.', 'It contains protein, minerals, vitamins, phycocyanin, and more.', 'It can be used across meals, seasonings, drinks, pet care, and sports nutrition.', 'It brings the life force of Earth’s oldest life into modern food.'],
    achieveCta: 'View Achieve collaboration products',
    confidenceLead: 'Gently refine with 97% pure natural silica.',
    confidenceBody: ['Confidence is a white powder born from Mother Vegetable.', 'As it grows, it produces 97% pure amorphous silica.', 'This silica also meets quasi-drug ingredient standards,', 'and can be used for skin, hair, and beloved pets,', 'or mixed with lotions and shampoos to upgrade everyday care.'],
    confidenceCta: 'View Confidence collaboration products',
    storySubtitle: ['Human passion. Japanese charm. Earth’s power.', 'A product that brings all of them together.'],
    storyDiagramTitle: 'The three forces behind MV Product',
    force1Title: 'Producer passion',
    force1Description: 'Who it is made for, and what future it imagines.',
    force2Title: ['Japanese materials', 'regional value'],
    force2Description: 'Materials, culture, craft, and stories rooted in each place.',
    force3Title: 'Mother Vegetable power',
    force3Description: 'Nutrition, purification, and regeneration from Earth’s oldest life.',
    searchTitle: ['Search by story, person, or country', 'and start exploring now'],
    searchSubtitle: 'An e-commerce experience where searching itself becomes fun',
    searchOptions: ['Search by story', 'Search by creator', 'Search by country'],
    searchNote: 'A Mother Vegetable search experience that makes discovery enjoyable.',
    searchCta: 'Try the search experience in all products →',
  },
  zh: {
    metaTitle: 'Mother Vegetable FMCG | 融合故事的产品与地球最初植物的力量',
    metaDescription: 'Mother Vegetable FMCG 源自融合故事的产品与地球最初植物的生命力。',
    heroTitle: 'Mother Vegetable FMCG',
    heroSubbrand: 'ALL MADE IN JAPAN',
    heroTagline: '融合故事的产品 × 地球最初植物的力量',
    heroCta: '查看 MV Product',
    aboutTitle: ['开发者故事', '与地球最初植物的融合'],
    aboutLead: ['日本各地孕育的饮食文化与技艺。', '孩子们想象未来的创意。', '运动员与生产者的挑战。'],
    aboutBody: ['Mother Vegetable FMCG', '将珍贵人们的故事', '与地球最初的生命相融合，', '连接地球、健康与未来，', '进化为全新的产品。'],
    productsTitle: ['源自 Mother Vegetable', '两种“地球最古老生命的力量”', '融入每一件商品'],
    achieveLead: '高蛋白＋48种天然营养',
    achieveBody: ['Achieve 是源自 Mother Vegetable 的高营养食品。', '含有蛋白质、矿物质、维生素、藻蓝蛋白等。', '可广泛用于餐食、调味、饮品、宠物与运动营养。', '为现代饮食加入地球最古老生命的力量。'],
    achieveCta: '查看 Achieve 联名商品',
    confidenceLead: '以97%纯天然二氧化硅，温和调理。',
    confidenceBody: ['Confidence 是源自 Mother Vegetable 的白色粉末。', '在生长过程中会生成纯度97%的非晶质二氧化硅。', '符合准药品原料规格，', '可用于肌肤、头发与宠物护理，', '也可加入化妆水或洗发水提升日常护理。'],
    confidenceCta: '查看 Confidence 联名商品',
    storySubtitle: ['人的心意。日本的魅力。地球的力量。', '将这一切融入产品。'],
    storyDiagramTitle: '构成 MV Product 的三种力量',
    force1Title: '生产者的心意',
    force1Description: '为了谁、怀着怎样的未来愿景而制作。',
    force2Title: ['日本素材', '地域魅力'],
    force2Description: '扎根土地的素材、文化、技艺与故事。',
    force3Title: 'Mother Vegetable 的力量',
    force3Description: '地球最古老生命拥有的营养、净化与再生之力。',
    searchTitle: ['从故事・人物・国家', '立即开始搜索'],
    searchSubtitle: '让搜索本身也变得有趣的电商体验',
    searchOptions: ['按故事搜索', '按发起人搜索', '按国家搜索'],
    searchNote: '让寻找本身也充满乐趣的 Mother Vegetable 搜索体验。',
    searchCta: '在商品列表体验搜索 →',
  },
} as const;
