import { setRequestLocale } from 'next-intl/server';

export default async function PrivacyPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <div className="bg-black min-h-screen py-8">
      <div className="max-w-[1000px] mx-auto px-5">
        <h1 className="text-center font-bold text-3xl md:text-4xl text-[#25C760] tracking-wider mb-8">PRIVACY POLICY</h1>

        <div className="text-white text-sm md:text-base leading-relaxed space-y-4">
          <p>Welcome to <strong>Mother Vegetable</strong>.</p>
          <p><strong>Mother Vegetable</strong> (&ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;) operates <strong>https://www.mothervegetable.com</strong> (hereinafter referred to as <strong>&ldquo;Service&rdquo;</strong>).</p>
          <p>Our Privacy Policy governs your visit to <strong>https://www.mothervegetable.com</strong>, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
          <p>We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy.</p>
          <p>Our Terms and Conditions (&ldquo;Terms&rdquo;) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (&ldquo;Agreement&rdquo;).</p>

          <h2 className="text-[#25C760] font-bold text-xl mt-8 mb-4">Definitions</h2>
          <p><strong className="text-[#25C760]">SERVICE</strong> means the https://www.mothervegetable.com website operated by Mother Vegetable.</p>
          <p><strong className="text-[#25C760]">PERSONAL DATA</strong> means data about a living individual who can be identified from those data.</p>
          <p><strong className="text-[#25C760]">USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself.</p>
          <p><strong className="text-[#25C760]">COOKIES</strong> are small files stored on your device (computer or mobile device).</p>

          <h2 className="text-[#25C760] font-bold text-xl mt-8 mb-4">Information Collection and Use</h2>
          <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
          <h3 className="text-[#25C760] font-semibold text-lg mt-4 mb-2">Personal Data</h3>
          <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
          <ul className="list-disc list-inside space-y-1 ml-4">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, Country, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ul>

          <h2 className="text-[#25C760] font-bold text-xl mt-8 mb-4">Use of Data</h2>
          <p>Mother Vegetable uses the collected data for various purposes:</p>
          <ul className="list-disc list-inside space-y-1 ml-4">
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
          </ul>

          <h2 className="text-[#25C760] font-bold text-xl mt-8 mb-4">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, please contact us through our official website.</p>
        </div>
      </div>
    </div>
  );
}
